name: "Ibis Next Builds"
description: "Automatically build new eBook PDF files using Ibis Next"
author: "Bobby Iliev"
inputs:
  ibis_path:
    description: "Path to your Ibis ebook"
    required: false
    default: "./"
  ibis_branch:
    description: "Branch to push the changes to"
    required: false
    default: "main"
  email:
    description: "Email id used while committing to the repo"
    required: false
    default: "bobby@bobbyiliev.com"
  commit_message:
    description: "The commit message"
    required: false
    default: "Updated Ibis Next Exported Files"
  php_version:
    description: "PHP version to use"
    required: false
    default: "8.2"
runs:
  using: "composite"
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php_version }}
        extensions: gd, zip, mbstring, intl
        coverage: none
    
    - name: Cache Composer packages
      uses: actions/cache@v4
      with:
        path: ~/.composer
        key: ${{ runner.os }}-composer-ibis-v2.0
        restore-keys: |
          ${{ runner.os }}-composer-ibis-
    
    - name: Install Ibis Next
      shell: bash
      run: composer global require hi-folks/ibis-next:^2.0 --optimize-autoloader
    
    - name: Build eBooks with Ibis Next
      shell: bash
      env:
        IBIS_PATH: ${{ inputs.ibis_path }}
        IBIS_BRANCH: ${{ inputs.ibis_branch }}
        EMAIL: ${{ inputs.email }}
        COMMIT_MESSAGE: ${{ inputs.commit_message }}
      run: ${{ github.action_path }}/entrypoint.sh
outputs:
  build_status:
    description: "Ibis Next build status"
    value: "completed"
branding:
  icon: "git-merge"
  color: "purple"
